<?php

namespace app\classes;

use Walker_Nav_Menu;

class Custom_walker extends Walker_Nav_Menu
{

    public function start_lvl(&$output, $depth = 0, $args = null)
    {
        // Depth-dependent classes.
        $indent = ($depth > 0 ? str_repeat("\t", $depth) : ''); // code indent
        $display_depth = ($depth + 1); // because it counts the first submenu as 0
        $classes = array(

        );
        $class_names = implode(' ', $classes);


        if ($depth ==1)
            $output .= "\n" . $indent . '<div class="row ' . $depth . '"><div class="container-fluid megamenu">' . "\n";
        else
            $output .= "\n" . $indent . '<ul class="' . $depth . '">' . "\n";
    }


    public function end_lvl(&$output, $depth = 0, $args = null)
    {
        if ($depth ==1)
            $output .= "\n" .'</div></div> ' . "\n";
        else
        parent::end_lvl($output, $depth, $args); // TODO: Change the autogenerated stub
    }

    public function start_el(&$output, $item, $depth = 0, $args = null, $id = 0)
    {


       if($depth==1)
       {

           $output .= '<li class="'.$depth.'"><a href="'.$item->url.'">'.$item->title.'</a>';

       }

    elseif ($depth==2)
           $output .= '<div class="megamenu_title"><a href="'.$item->url.'"><span>'.$item->title.'</span></a></div><div class="col-3 col-md-10 '.$depth.'">';
       elseif ($depth==3)
           $output .= '<li class=" '.$depth.'"><a href="'.$item->url.'">'.$item->title.'</a>';
           else
            parent::start_el($output, $item, $depth, $args, $id); // TODO: Change the autogenerated stub
      //  $output .= '<div>';
    }

    public function end_el(&$output, $item, $depth = 0, $args = null)
    {
        if($depth==1)
            $output .= '</li>';

        elseif ($depth==2)
            $output .= '</div><div class="col-6 col-md-4 megamenu_image"><img src="'.$item->description.'"  alt=""/> </div>';
        elseif ($depth==3)
            $output .= '</li>';
        else
        parent::end_el($output, $item, $depth, $args); // TODO: Change the autogenerated stub
    }

}